name: Build NixOS-WSL Installer

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    
    - uses: DeterminateSystems/nix-installer-action@main
    
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - uses: DeterminateSystems/flake-checker-action@main
    
    - name: Build WSL Tarball
      id: build
      run: |
        nix build .#nixosConfigurations.thixos.config.system.build.tarball
        mv result/nixos-wsl-x86_64-linux.tar.gz thixos.wsl
        echo "Build complete."

    - uses: actions/upload-artifact@v6
      with:
        name: thixos-wsl-installer
        path: thixos.wsl
        if-no-files-found: error
        
